### ISSUE TITLE
add a platformId attribute to the bolide object

### ISSUE THREAD

**Issue by jessie-dotson** [jcsmithhere/bolides#1]
It would be super useful if the bolide objects included a platformId attribute.  I *think* the following code bit if added to bolide.py would do it, but I'm a bit clueless on how to test a change to a package on my own system...  (Much less how to submit a pull request.)  

@property
    def platformId(self):
        return [self.json['attachments'][idx]['platformId']
               for idx in range(len(self.json['attachments']))]

**Comment by jcsmithhere** [comment]
I believe this is OBE due to the new bdf-implementation release. Closing as "Won't fix".
