### ISSUE TITLE
Set up a pyproject.toml

### ISSUE THREAD

**Issue by jcsmithhere** [jcsmithhere/bolides#11]
Set up a pyproject.toml, which is a superior replacement for setup.py. 

There are several python package management tools. We should make sure it works with pip as a minimum but poetry is now used a lot. We should also make sure it works with conda, but pip usually does, in it's awkward way.

Also, any bolide pipeline module dependencies must be optional because that code is internal to NASA, for now.

Also, we should make sure we can install the package in editable mode via pip:
`pip install -e .`
which I think means we still need a setup.py

**Comment by anthonyozerov** [comment]
Just set up and tested in https://github.com/jcsmithhere/bolides/commit/9b2c725e89ea1b46372d0bcf69069f6ab8a4c15f in [bdf-implementation](https://github.com/jcsmithhere/bolides/tree/bdf-implementation). I wasn't sure what info to put for author and maintainers so I just put my name and email to see how it works.

I was able to package it with `setuptools` (`python3 -m build`) and use `twine` (`python3 -m twine upload --repository testpypi dist/*`) to upload it to [TestPyPI](https://test.pypi.org/project/bolides/) to see how packaging and uploading to PyPI will eventually work.

It can (hypothetically) be installed with `pip install -i https://test.pypi.org/simple/bolides`, but I messed up some dependencies in the version I uploaded so you need to do `pip install -i https://test.pypi.org/simple/ --no-deps bolides` and manually install dependencies. This has been fixed (but not tested!) in the pyproject.toml added in https://github.com/jcsmithhere/bolides/commit/9b2c725e89ea1b46372d0bcf69069f6ab8a4c15f.

Also need to figure out what specific versions of the dependencies (and Python itself) are required for the package to work.

I think you are correct that we still need a setup.py, as I tried doing `pip install -e .` and it did not seem to use pyproject.toml.

**Comment by anthonyozerov** [comment]
Made a bunch of fixes and improvements in https://github.com/jcsmithhere/bolides/commit/46da02f6bda1d565764fa43cf768eda6919d8fc2 in [bdf-implementation](https://github.com/jcsmithhere/bolides/tree/bdf-implementation):
- Added installation instructions to  [README.rst](https://github.com/jcsmithhere/bolides/tree/bdf-implementation#readme)
- No more messed-up dependencies (as long as the instructions are followed!). Of course this needs to be tested on other systems though. I will test on the NAS at some point. Also needs to be tested with conda (would be nice to check that it works in the atap-glm environment… I will try it at some point)
- Migrated completely to pyproject.toml. setup.py contains just enough information for `pip install -e .` to work (it apparently pulls dependency and version information from pyproject.toml, but still needs a couple things).
- Data like the GLM FOV is now correctly included in the package.
- Several fixes to how data files referenced in the code to make everything work correctly when packaged.

**Comment by jcsmithhere** [comment]
I have successfully followed the installation instructions on both a mac and linux. cartopy installed perfectly fine using conda. 

The instructions are clear to me, but I am not a good test case. 

@anthonyozerov, I believe you can close this ticket.
