### ISSUE TITLE
Cannot load from pipeline database files

### ISSUE THREAD

**Issue by jcsmithhere** [jcsmithhere/bolides#12]
When trying:

`bdf = BolideDataFrame(source='pipeline', files=[database_file_G16, database_file_G17])`

I get the following error: 

> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> Input In [3], in <cell line: 1>()
> ----> 1 bdf = BolideDataFrame(source='pipeline', files=[database_file_G16, database_file_G17])
> 
> File ~/dev_atap/bolides-bdf/bolides/bdf.py:124, in BolideDataFrame.__init__(self, *args, **kwargs)
>     121     init_gdf = GeoDataFrame(init_gdf, geometry=points, crs="EPSG:4326")
>     123 elif source == 'pipeline':
> --> 124     init_gdf = pipeline()
>     125     init_gdf['source'] = 'pipeline'
>     127 # rearrange columns, respecting original order if csv or pickle
> 
> TypeError: pipeline() missing 1 required positional argument: 'files'

Looks like the code to load in database files is not complete.

Also, looks like ZODB is a dependency but not installed as a requirement. Given right now most people will not be using the pipeline database files, perhaps we could make ZODB an optional dependency? I've never done this myself but have heard it can be done.

**Comment by jcsmithhere** [comment]
Assigning bug ticket to @anthonyozerov

**Comment by jcsmithhere** [comment]
BTW, if I fix the dependencies and fix the error above about missing arguments, I can get the code to run and analyze the data.

**Comment by anthonyozerov** [comment]
Pipeline import fixed in 8dda04cbac2e2d5e9b706d9ee14827a703283769. Support for ZODB as an optional dependency added in bacbf692733adda98e4778eb281ce4c75bf51d23, so now installing the dependencies for the pipeline can be done by appending `[pipeline]` to the pip install command.
