### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by anthonyozerov** [jcsmithhere/bolides#13]
Since this is open-source software, we should think about how to license the package. There are lots of options but a permissive open-source license like the MIT license or the BSD 3-clause is usually a good choice for stuff like this.

**Comment by jcsmithhere** [comment]
Yes, I see there was no license set up when the repo was first created. I'm good with the MIT license.

Also, I am thinking once we release this we should move it to the seti.org github site instead of my personal site.

**Comment by jcsmithhere** [comment]
MIT license added. Closing issue.
