### ISSUE TITLE
ImportError: cannot import name 'BolideDataFrame' from 'bolides'

### ISSUE THREAD

**Issue by whifee** [jcsmithhere/bolides#15]
When I use AWS Sagemaker Studio or Google Colab free web notebooks - after installs of different relevant packages I end up getting some version of this error: `ImportError: cannot import name 'BolideDataFrame' from 'bolides' (/usr/local/lib/python3.7/dist-packages/bolides/__init__.py)` like it may not exist.  

Here are the commands I ran prior to error in Google Colab:
- !pip install bolides
- !pip install lightkurve
- !pip install pytube
- from bolides import BolideDataFrame

**Comment by jcsmithhere** [comment]
@whifee, the version of the bolides package on pip is the old version. We have a radically updated release on the branch "bdf-implementation". You will need to install that by cloning the git repo by following the instructions on https://bolides.readthedocs.io/en/latest/installation.html

Sorry about this! We are going to merge this branch to master and make pip installable very soon!

**Comment by whifee** [comment]
I was able to get this working locally doing a `pip install -e` from the branch -- but that didn't work in web notebooks FYI (Google Colab or AWS Sagemaker).  Closing this out though since I was able to get information for our purposes of the classified bolides.
