### ISSUE TITLE
install requirement list is missing pytube and opencv-python

### ISSUE THREAD

**Issue by jessie-dotson** [jcsmithhere/bolides#4]
(I thought about adding them to the setup.py file and submitting it as a PR, but when I looked up all the steps, I chickened out!  lol)

bolides requires pytube and opencv-python, but these aren't in the install requirement list.

**Comment by jcsmithhere** [comment]
I'm closing this ticket as "Won't fix" because it is OBE (overcome by events). The new release on branch bdf-implementation resolves this issue.

**Comment by jcsmithhere** [comment]
Closing
