### ISSUE TITLE
Write README.rst

### ISSUE THREAD

**Issue by jcsmithhere** [jcsmithhere/bolides#5]
We need an intro README!

Include an introduction and some basic examples of functionality. The README should be a very quick introduction to the package to give users within a couple minutes a good idea of what functionality the package provides. Pretty pictures and animations are always good! Then at the end of the README the user is referred to the Jupyter notebook tutorial for more details.

**Comment by anthonyozerov** [comment]
Started in 5ec1366dfef1cd324e55fcf197b20065bd5a4366 in [bdf-implementation](https://github.com/jcsmithhere/bolides/tree/bdf-implementation) Should add photos, animations of usage. A good animation would maybe be one like in the README of [lightkurve](https://github.com/lightkurve/lightkurve) which highlights how easy the package is to use.

**Comment by jcsmithhere** [comment]
Your ideas all sound good, @anthonyozerov !

**Comment by jcsmithhere** [comment]
I recommend adding a couple pretty figures to the README.rst to draw in the user. Perhaps a good figure of a globe scatter plot, a time histogram and a bolide light curve. Some eye candy to attract a user.

**Comment by anthonyozerov** [comment]
Just added a preview gif demonstrating some plotting in 50e6d309a882dcc95fbdd29578fbeaa63b66a87b.

**Comment by jcsmithhere** [comment]
Your preview gif looks great! I recommend slowing down the speed. The commands scroll off screen very quickly and is difficult to read what you typed in time before it's gone.
