### ISSUE TITLE
Create Jupyter notebook tutorial

### ISSUE THREAD

**Issue by jcsmithhere** [jcsmithhere/bolides#6]
We need a tutorial. A Jupyter Notebook seems like a reasonable vehicle for said tutorial.

**Comment by anthonyozerov** [comment]
The tutorial notebook has been updated in 9b2c725e89ea1b46372d0bcf69069f6ab8a4c15f to reflect changes in the FOV data and additionally cover:
- Using  `clip_boundary` to filter by FOV
- Using `augment` to combine data from multiple sources

Still need to add an intro and more exposition.

**Comment by jcsmithhere** [comment]
Tutorial looks good. One recommendation:

- Provide a brief description of what is the "USG" data and what is the pipeline data. Mention that the pipeline data is not currently publicly available but one can contact me to discuss obtaining the data.

Other than that, the tutorial looks good to me. However, I am not the best critic. We need someone not involved in the project to assess it.
