### ISSUE TITLE
Ability to search database by date, satellite, lat/lon, etc...

### ISSUE THREAD

**Issue by jcsmithhere** [jcsmithhere/bolides#8]

**Comment by anthonyozerov** [comment]
Implemented in 404c8b2c6b00ee2c7d3fd50f3b22fdeed91687a9 in [bdf-implementation](https://github.com/jcsmithhere/bolides/tree/bdf-implementation), API described in #10. Only difference is that the three date-filtering methods have been replaced with `filter_date`. An example of usage is `bdf.filter_date(start='2020-01-01', end='2021-05-03')`. The start and end arguments can be omitted to only filter out in one direction.

[bdf-implementation](https://github.com/jcsmithhere/bolides/tree/bdf-implementation) now also includes the `get_closest_by_time` and `get_closest_by_loc` methods to get the closest bolides to a particular time or location (c9d59929db444b5356c75942c4139c8178a3bd57). An example of usage is `bdf.get_closest_by_time('2021-01-02 13:00:21', n=2)` to get the closest 2 bolides to that time.

Also, [bdf-implementation](https://github.com/jcsmithhere/bolides/tree/bdf-implementation) includes the `clip_boundary` method to filter a BolideDataFrame by FOV (c9d59929db444b5356c75942c4139c8178a3bd57), supporting GOES-East and GOES-West GLM fields of view. Here is an example of how to filter USG data to the GLM fields of view:

```
bdf = BolideDataFrame(source='usg')
bdf.plot_detections()
plt.show()
```
![clip-demo-before](https://user-images.githubusercontent.com/44622237/174415102-c190dd5f-313d-4c9b-bb19-c366813fe24b.png)
```
bdf = bdf.clip_boundary(boundary=['goes-w','goes-e'], intersection=False)
bdf.plot_detections()
plt.show()
```
![clip-demo](https://user-images.githubusercontent.com/44622237/174415059-dd0f5244-6860-4ae1-8479-7fc0eb9d57bf.png)
```
bdf = bdf.clip_boundary(boundary=['goes-w','goes-e'], intersection=True)
bdf.plot_detections()
plt.show()
```
![clip-demo-intersection](https://user-images.githubusercontent.com/44622237/174415172-a2acd985-5a3c-4f67-9f8b-691fbb2e513e.png)

**Comment by jcsmithhere** [comment]
This all looks good, @anthonyozerov , of course, an example with the neo-bolides website data would be good, but happy to see it is easy to import the USG data as well. I wonder how many other meteor data sets we could easily import.

**Comment by jcsmithhere** [comment]
I believe this ticket can be closed.
