### ISSUE TITLE
Switch from Basemap to Cartopy

### ISSUE THREAD

**Issue by jcsmithhere** [jcsmithhere/bolides#9]
The current plotting tools uses Basemap, which is Matplotlib’s old globe plotting tools. Switch to use Cartopy, which is the new tool.

**Comment by anthonyozerov** [comment]
Done in the `plot_detections` method of `BolideDataFrame` in [bdf.py](https://github.com/jcsmithhere/bolides/blob/bdf-implementation/bolides/bdf.py) in the `bdf-implementation` branch.
Done by:
- Getting a GeoPandas-accepted projection object from a given Cartopy `CoordinateReferenceSystem`
- Reprojecting the data in the `BolideDataFrame` using the `to_crs` method inherited from `GeoDataFrame`
- Creating a plot with the given CoordinateReferenceSystem
- Plotting the data, boundaries, etc using regular matplotlib syntax

The `plot_map` method of `BolideList` has not been changed on the assumption that `BolideList` will be superceded by `BolideDataFrame`.

**Comment by jcsmithhere** [comment]
@anthonyozerov, To keep track of where the issue was fixed, you should link the branch where the issue was resolved. 
To be pedantic, as professional software engineers, we would then confirm the issue is fixed in the branch before merging to the PR to the main branch.
